language: rust
matrix:
  fast_finish: true
  include:
    # =====================================================================
    # Stable
    # =====================================================================
    - rust: stable
      name: check
      script:
        - cargo test --all
