[workspace]

members = [
    "netlink-sys",
    "netlink-packet-core",
    "netlink-packet-utils",
    "netlink-packet-route",
    "netlink-packet-route/examples/dump_links",
    "netlink-packet-audit",
    "netlink-packet-sock-diag",
    "netlink-proto",
    "rtnetlink",
    "audit",
]
